name       : xkill
version    : 1.0.4
release    : 3
source     :
    - https://www.x.org/releases/individual/app/xkill-1.0.4.tar.gz : f80115f2dcca3d4b61f3c28188752c21ca7b2718b54b6e0274c0497a7f827da0
license    :
    - MIT
component  : xorg.apps
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
summary    : |
    X.Org Applications: xkill
description: |
    X.Org Applications: xkill
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
