name       : xkill
version    : 1.0.5
release    : 9
source     :
    - https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz : 98fab8a8af78d5aae4e1f284b580c60e3d25ed2a72daa4dbce419b28d8adaf8a
license    : MIT
component  : xorg.apps
summary    : |
    X.Org Applications: xkill
description: |
    X.Org Applications: xkill
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
